[build]
command = "npm i && npx prisma db pull && npx prisma generate && npm run build && npm run build:functions"
functions = "functions-build"
# always appends `-build` folder to your `functions` folder for builds